changelog:
  exclude:
    authors:
      - github-actions
  categories:
    - title: New Features 🎉
      labels:
        - "enhancement"
    - title: Bug Fix 🐛
      labels:
        - "bug"
    - title: Improvement 🚀
      labels:
        - "improvement"
    - title: Documentation 📝
      labels:
        - "documentation"
    - title: Other Changes 🛠
      labels:
        - "*"
