name: Manual Publish Package

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"

      - name: Package Install
        run: pnpm install

      - name: Build
        run: pnpm run build:ci

      - name: Publish npm package
        run: pnpm publish --recursive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
