name: Manual Publish Package

on:
  workflow_dispatch:
    inputs:
      semantic_stage:
        description: "Semantic release stage"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"

      - name: Package Install
        run: npm ci

      - name: Semantic Version Increment
        run: npm version ${{ github.event.inputs.semantic_stage }} --no-git-tag-version

      - name: Diff Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          DATE=$(TZ=Asia/Tokyo date +'%Y-%m-%d %H:%M:%S')
          git add package.json
          git diff --quiet || git commit -m ":green_heart: Auto increment version in github actions workflow on $DATE"
          git push origin HEAD

      - name: Build
        run: npm run build --workspaces

      - name: Publish npm package
        run: npm publish --workspaces
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
